### ISSUE TITLE
Mosaic Content Tile: 2 pts

### ISSUE THREAD

**Issue by skleinfeldt** [PSUEducationalEquity/plonetheme.eeq#28]
As a user I can see a tile with a full-bleed image at the top, followed by title and summary on white, and a thin black line around it, as shown at the bottom of the homepage mockup. The title is a link to a content item on the site. These tiles will resize at smaller screen sizes and the images will be dropped at the smallest screen sizes. (See mockup for responsive behavior.) 

As an editor I can create one of these tiles by choosing an existing site content item that has a lead image.

- [x] customize jazkarta.tessarae summary tile
-  ~make sure responsive styling is working, adjust styling if needed~

**Comment by skleinfeldt** [comment]
Implementation will be jazkarta.tesserae - see doaks.org for examples

**Comment by witekdev** [comment]
@paulrentschler I've pushed this to master. It should be looking pretty decent, baring the responsive/breakpoints work that will come later.

There is one issue that I'm aware of that may or may not apply, namely in the case where text descriptions are of various lengths, the tile heights might vary in a 3 or 2 column layout. With the current mosaic html classes, I didn't see an easy way to customize this in styling, perhaps we need to add some extra classes/markup with diazo, if this crops up.

**Comment by paulrentschler** [comment]
@witekdev what am I selecting from the insert menu to use this? I tried Existing Content and Collection Summary neither of which worked. I also tried Content Summary which is likely it.

I have 2 Content Summary tiles and an Existing Content tile on this page: https://beta.equity.psu.edu/web/not-home

**Comment by witekdev** [comment]
@paulrentschler its the "Content Summary" tile, correct. 
That page looks more or less good, except the images on the pieces of content are not quite big enough likely?

**Comment by paulrentschler** [comment]
@witekdev okay and yes the images I used were pretty small (too small to apply the cropping to them) so the issue is likely on my end. Thanks.

**Comment by paulrentschler** [comment]
Yep, bigger images did the trick. Now it looks like the original mock ups.

**Comment by paulrentschler** [comment]
These tiles are behaving as expected at different responsive breakpoints with the only issue being the one Witek raised earlier about the boxes not being the same height in a multi-column layout. That is definitely an issue that will need to be resolved.

Also, I noticed that if I expire the item that the tile is connected, I get an error:
![image](https://user-images.githubusercontent.com/1778602/123477418-0a6ea480-d5cc-11eb-8525-4a6b5274c8ab.png)

Not sure if this will actually present a problem or not.

Related question: was the intent to use these Content Tiles to also render the news items on the Office home pages? If so that is going to present a problem because these have to be manually placed and removed and I would want the office home page news to be based on a collection so it is dynamically rendered. And that leads to maybe this home page listing would be better handled with a Content Summary or Collection Summary type Mosaic element that Diazo turns into the appropriate Bootstrap grid tiles.

**Comment by skleinfeldt** [comment]
Needs work: keeping ties within a row to the same height.

**Comment by skleinfeldt** [comment]
@alecpm when you review the PR please adjust the image cropping settings to turn on auto cropping for the custom crop sizes.

**Comment by skleinfeldt** [comment]
@alecpm will also adjust the image crop sizes based on the new aspect ratios @ will provide on #25.

**Comment by silviot** [comment]
The current behavior is OK, so this does not require additional work.

**Comment by MBrahosky** [comment]
Height The height for the Mosaic content summary tile is not aligning with other tiles.
(see example.) https://beta.equity.psu.edu/web/home

**Comment by alecpm** [comment]
@MBrahosky for rows where you want the tile heights to expand to fill the full column, you need to select the "Equal Height Tiles" Row format from the Format menu in the mosaic edit view after selecting a tile from the row. I've done that for both of the rows in the page above. I think maybe the row format should be called "Equal height columns" because that's actually what it ends up doing (though it also expands the tiles to fill the columns, so maybe the name is fine).

**Comment by paulrentschler** [comment]
@alecpm excellent. Did not realize there was a format that we needed to apply. This looks good to me but I will let @MBrahosky weigh in as well.

**Comment by MBrahosky** [comment]
@alecpm This looks good to me. (Obliviously, the content will be abbreviated for each office in an effort to keep some uniformity within the columns.) But, the "Equal height columns" is what we were aiming for. Excellent.

**Comment by MBrahosky** [comment]
![break-point-fix](https://user-images.githubusercontent.com/7536857/150003283-e70c387b-c64e-4059-9db7-9936ee74ccfc.png)
 
Break point needs to be corrected. (See screen image.) Paul suggests a possible CSS rule may have been deleted in this story.

**Comment by alecpm** [comment]
Because the equal height column config now uses flex box it's not changing the column layout based on breakpoint. It looks like changing the `.mosaic-grid-row.mosaic-row-equal-height` styling from `flex-wrap: nowrap` to `flex-wrap: wrap` fixes the issue while retaining the equal heights. I'll get that corrected.

**Comment by alecpm** [comment]
@paulrentschler I've pushed an update to the add-on that provides the equal height tile format, you'll need to re-run buildout (and maybe `bin/develop up`) and restart the instances to get the correct behavior. If you have a proxy cache in front of it, you may need to clear the cache to get fresh CSS for the add-on.

**Comment by paulrentschler** [comment]
@alecpm I tried running Buildout and it errored out:

```
par117@eeqdemo02:/opt/current-plone/zeocluster$ sudo -u plone_buildout ./bin/buildout -c develop.cfg
Getting distribution for 'collective.xmltestreport==2.0.2'.
Got collective.xmltestreport 2.0.2.
Getting distribution for 'zope.testrunner==5.2'.
Got zope.testrunner 5.2.
Uninstalling theme-compile.
Running uninstall recipe.
Uninstalling npm-install.
Running uninstall recipe.
Uninstalling precompiler.
Uninstalling zopepy.
Uninstalling client2.
Uninstalling client1.
Updating _mr.developer.
Updating zeoserver.
Installing client1.
Getting distribution for 'plone.reload==3.0.1'.
Got plone.reload 3.0.1.
Generated script '/opt/plone-5.2.4/zeocluster/bin/client1'.
Generated interpreter '/opt/plone-5.2.4/zeocluster/parts/client1/bin/interpreter'.
Installing client2.
Generated script '/opt/plone-5.2.4/zeocluster/bin/client2'.
Generated interpreter '/opt/plone-5.2.4/zeocluster/parts/client2/bin/interpreter'.
Updating backup.
Updating zopescripts.
Generated script '/opt/plone-5.2.4/zeocluster/bin/addzope2user'.
Generated script '/opt/plone-5.2.4/zeocluster/bin/mkwsgiinstance'.
Generated script '/opt/plone-5.2.4/zeocluster/bin/runwsgi'.
Generated script '/opt/plone-5.2.4/zeocluster/bin/zconsole'.
Installing zopepy.
Generated interpreter '/opt/plone-5.2.4/zeocluster/bin/zopepy'.
Updating unifiedinstaller.
Updating setpermissions.
setpermissions: Running # Dummy references to force this to execute after referenced parts
echo /opt/plone-5.2.4/zeocluster/var/backups yes > /dev/null
chmod 600 .installed.cfg
# Make sure anything we've created in var is r/w by our group
find /opt/plone-5.2.4/zeocluster/var -type d -exec chmod 770 {} \; 2> /dev/null
find /opt/plone-5.2.4/zeocluster/var -type f -exec chmod 660 {} \; 2> /dev/null
find /opt/plone-5.2.4/zeocluster/var -type d -exec chmod 770 {} \; 2> /dev/null
find /opt/plone-5.2.4/zeocluster/var -type f -exec chmod 660 {} \; 2> /dev/null
chmod 754 /opt/plone-5.2.4/zeocluster/bin/*
chmod: changing permissions of '/opt/plone-5.2.4/zeocluster/bin/python': Operation not permitted
chmod: changing permissions of '/opt/plone-5.2.4/zeocluster/bin/python3': Operation not permitted
chmod: changing permissions of '/opt/plone-5.2.4/zeocluster/bin/python3.8': Operation not permitted
Installing precompiler.
Compiling Python files.
  File "/opt/plone-5.2.4/buildout-cache/eggs/cp38/plone.staticresources-1.4.2-py3.8.egg/plone/staticresources/static/components/jqtree/_entries/insert.py", line 44
    print 'rename %s to %s' % (old_filename, new_filename)
          ^
SyntaxError: invalid syntax

  File "/opt/plone-5.2.4/buildout-cache/eggs/cp38/plone.staticresources-1.4.2-py3.8.egg/plone/staticresources/static/components/jqtree/_entries/renumber.py", line 36
    print 'rename %s to %s' % (old_filename, new_filename)
          ^
SyntaxError: invalid syntax

/opt/plone-5.2.4/buildout-cache/eggs/cp38/plone.app.contenttypes-2.2.2-py3.8.egg/plone/app/contenttypes/migration/utils.py:504: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if source_type is 'DX':
/opt/plone-5.2.4/buildout-cache/eggs/cp38/plone.app.contenttypes-2.2.2-py3.8.egg/plone/app/contenttypes/migration/utils.py:507: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if target_type is 'AT' and not is_referenceable(source_obj):
  File "/opt/plone-5.2.4/buildout-cache/eggs/cp38/zodbpickle-2.0.0-py3.8-linux-x86_64.egg/zodbpickle/pickletools_2.py", line 1803
    print "skipping %r: it doesn't look like an opcode name" % name
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("skipping %r: it doesn't look like an opcode name" % name)?

  File "/opt/plone-5.2.4/buildout-cache/eggs/cp38/zodbpickle-2.0.0-py3.8-linux-x86_64.egg/zodbpickle/pickle_2.py", line 882
    except _Stop, stopinst:
                ^
SyntaxError: invalid syntax

  File "/opt/plone-5.2.4/buildout-cache/eggs/cp38/zodbpickle-2.0.0-py3.8-linux-x86_64.egg/zodbpickle/tests/pickletester_2.py", line 433
    x = [0, 1L, 2.0, 3.0+0j]
             ^
SyntaxError: invalid syntax

Compiling locale files.
Installing test.
Generated script '/opt/plone-5.2.4/zeocluster/bin/test'.
Installing diazotools.
Generated script '/opt/plone-5.2.4/zeocluster/bin/diazocompiler'.
Generated script '/opt/plone-5.2.4/zeocluster/bin/diazorun'.
Generated script '/opt/plone-5.2.4/zeocluster/bin/diazopreprocessor'.
Installing checkdocs.
Getting distribution for 'collective.checkdocs'.
WARNING: The easy_install command is deprecated and will be removed in a future version.
Got collective.checkdocs 0.2.
Installing mrbob.
Getting distribution for 'mr.bob'.
WARNING: The easy_install command is deprecated and will be removed in a future version.
Traceback (most recent call last):
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ttgxop73/mr.bob-0.1.2/setup.py", line 41, in <module>
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_py')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/build_py.py", line 53, in run
    self.build_package_data()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/build_py.py", line 121, in build_package_data
    self.mkpath(os.path.dirname(target))
  File "/usr/lib/python3.8/distutils/cmd.py", line 338, in mkpath
    dir_util.mkpath(name, mode, dry_run=self.dry_run)
  File "/usr/lib/python3.8/distutils/dir_util.py", line 70, in mkpath
    os.mkdir(head, mode)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 311, in wrap
    return original(path, *args, **kw)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u030c' in position 41: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 2317, in main
    setup(
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ttgxop73/mr.bob-0.1.2/setup.py", line 41, in <module>
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_py')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/build_py.py", line 53, in run
    self.build_package_data()
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/command/build_py.py", line 121, in build_package_data
    self.mkpath(os.path.dirname(target))
  File "/usr/lib/python3.8/distutils/cmd.py", line 338, in mkpath
    dir_util.mkpath(name, mode, dry_run=self.dry_run)
  File "/usr/lib/python3.8/distutils/dir_util.py", line 70, in mkpath
    os.mkdir(head, mode)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/setuptools/sandbox.py", line 311, in wrap
    return original(path, *args, **kw)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u030c' in position 41: ordinal not in range(256)
An error occurred when trying to install /opt/plone-5.2.4/buildout-cache/downloads/dist/mr.bob-0.1.2.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing mrbob.
  Getting distribution for 'mr.bob'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/opt/plone-5.2.4/buildout-cache/eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/opt/plone-5.2.4/buildout-cache/eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
  File "/opt/plone-5.2.4/buildout-cache/eggs/cp38/zc.recipe.egg-2.0.7-py3.8.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 682, in install
    for dist in self._get_dist(requirement, ws):
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/opt/plone-5.2.4/zeocluster/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by alecpm** [comment]
It seems like your buildout suddenly pulling in older non-python 3 compatible versions of some core packages. I'm not sure what could have caused this, but I'm fairly certain it wasn't the CSS update in `jazkarta.tesserae` that this most recent fix entailed. Do you know when the last time you successfully ran buildout and if anything might have changed since then?

It looks like it's trying to run some buildout parts that I wouldn't expect (`precompiler`, `mrbob`), and which don't seem to be referenced anywhere in the codebase.

**Comment by paulrentschler** [comment]
@alecpm thanks for jogging my memory. I'm an idiot. I ran `./bin/buildout -c develop.cfg` instead of `./bin/buildout -c deploy.cfg`. Apparently I was not thinking this morning.

It has run successfully now. The tiles seem to be working correctly as well. Mike and I plan to review everything tomorrow (Friday). Thanks!
